name: First Step to CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Install Google Chrome
      run:  |
            chmod +x ./scripts/InstallChrome.sh
            ./scripts/InstallChrome.sh
    - name: Checkout selenium script
      uses: actions/checkout@main
      with:
        repository: gebynab/SeleniumTry
        path: './SeleniumTry'
    - name: Show working directory
      run: ls
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run selenium script
      run: |
           cd ./SeleniumTry
           mvn test