name: First Step to CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Buidling Container
      run : docker build -t my-apache2 .
    - name: Run Docker
      run : docker run -d -p 80:80 --name docker-apache -d my-apache2
    - name : Check Server
      run : curl http://localhost:80
    - name: Install Google Chrome
      run:  |
            chmod +x ./scripts/InstallChrome.sh
            ./scripts/InstallChrome.sh
    - name: Checkout Selenium Script
      uses: actions/checkout@main
      with:
        repository: gebynab/SeleniumTry
        path: './SeleniumTry'
    - name: Show Working Directory
      run: ls
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run selenium script
      run: |
           cd ./SeleniumTry
           mvn test
    - name : stop docker
      run : docker stop docker-apache